apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-example-deployment-2-replicas
spec:
  selector:
    matchLabels:
      app: spring-example
  replicas: 2
  template:
    metadata:
      labels:
        app: spring-example
    spec:
      containers:
      - name: spring-example
        image: spring-boot-openshift:0.0.1
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 60
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests:
            cpu: "200m"
            memory: "200Mi"
          limits:
            cpu: "1"
            memory: "1Gi"